### ISSUE TITLE
Unable to activate the app

### ISSUE THREAD

**Issue by steph-ben** [juliushaertl/direct_menu#53]
I got the following error when trying to activate the app:

```
root@soif:/usr/share/owncloud/apps# git clone https://github.com/juliushaertl/direct_menu.git
root@soif:/usr/share/owncloud/apps# sudo -u www-data occ app:enable direct_menu
An unhandled exception has been thrown:
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "direct_menu.App.stylesheet" as such route does not exist. in /usr/share/php/Symfony/Component/Routing/Generator/UrlGenerator.php:134
Stack trace:
#0 /usr/share/owncloud/lib/private/route/router.php(260): Symfony\Component\Routing\Generator\UrlGenerator->generate('direct_menu.App...', Array, false)
#1 /usr/share/owncloud/lib/private/urlgenerator.php(41): OC\Route\Router->generate('direct_menu.App...', Array)
#2 /usr/share/owncloud/apps/direct_menu/appinfo/app.php(24): OC\URLGenerator->linkToRoute('direct_menu.App...')
#3 /usr/share/owncloud/lib/private/app.php(113): require_once('/usr/share/ownc...')
#4 /usr/share/owncloud/lib/private/app.php(95): OC_App::requireAppFile('direct_menu')
#5 /usr/share/owncloud/lib/private/app.php(75): OC_App::loadApp('direct_menu')
#6 /usr/share/owncloud/console.php(29): OC_App::loadApps()
#7 /usr/share/owncloud/occ(11): require_once('/usr/share/ownc...')
#8 {main}
```

I'm using version

```
root@soif:/usr/share/owncloud/apps# occ --version
ownCloud version 7.0.4
```

**Comment by eppfel** [comment]
Sry, but the current version of this app needs at least version 9 of ownCloud or Nextcloud. You could switch to an older version of the app: https://github.com/juliushaertl/direct_menu/releases/tag/v0.9.2

```
$ git checkout tags/v0.9.2
````

But I would really recommend updating your ownCloud or switch to to Nextcloud!
